### ISSUE TITLE
[Bug]: WG

### ISSUE THREAD

**Issue by Diezel0468** [ZombieStriker/QualityArmory#276] opened 2022-02-03 13:40 UTC
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

console errors related to worldguard. They constantly appear.

### Expected Behaviour

fixes

### Server Version

1.17.1

### Relevant log output

```shell
[QualityArmory] Task #356718 for QualityArmory v2.0.5.1 generated an exception
java.lang.ClassCastException: class java.util.Optional cannot be cast to class me.zombie_striker.qg.hooks.protection.worldguard.flag.WrappedState (java.util.Optional is in module java.base of loader 'bootstrap'; me.zombie_striker.qg.hooks.protection.worldguard.flag.WrappedState is in unnamed module of loader 'QualityArmory (1).jar' @206a0736)
        at me.zombie_striker.qg.hooks.protection.implementation.WorldGuardHook.canPvp(WorldGuardHook.java:39) ~[QualityArmory (1).jar:?]
        at me.zombie_striker.qg.hooks.protection.ProtectionHandler.lambda$canPvp$1(ProtectionHandler.java:37) ~[QualityArmory (1).jar:?]
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
        at java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1728) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637) ~[?:?]
        at me.zombie_striker.qg.hooks.protection.ProtectionHandler.canPvp(ProtectionHandler.java:37) ~[QualityArmory (1).jar:?]
        at me.zombie_striker.qg.miscitems.Molotov$1.run(Molotov.java:76) ~[QualityArmory (1).jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-408]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-408]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Lorenzo0111** [comment] 2022-02-03 20:08
Duplicate of #273

**Closed by Lorenzo0111** 2022-02-03 20:08 UTC
Labels: duplicate
