### ISSUE TITLE
removes all teams and adds 22 new teams on start, it should be adjustable in the configuration

### ISSUE THREAD

**Issue by olebeck** [ZombieStriker/QualityArmory#10] opened 2018-09-03 14:33 UTC

**Comment by ZombieStriker** [comment] 2018-09-05 23:50
This is caused by the gloweffects. Seems it was accidentally enabled by default in the config.yml. This will be fixed soon. For now, disable glow effects in the config and it should no longer appear.

**Closed by ZombieStriker** 2018-09-05 23:50 UTC
