### ISSUE TITLE
[Bug]: #415 is not fixed

### ISSUE THREAD

**Issue by WongIong** [ZombieStriker/QualityArmory#457] opened 2023-02-27 14:56 UTC
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

Bullet was set to 0 when using scope

### Expected Behaviour

it shouldnt set the bullet

### Plugins

no

### Server Version

Paper 1.16.5

**Comment by Lorenzo0111** [comment] 2023-04-08 13:16
Duplicate of #415

**Closed by Lorenzo0111** 2023-04-08 13:16 UTC
Labels: bug, status: needs triage
