### ISSUE TITLE
[Bug]: Unlimited ammo but it's disabled in the config

### ISSUE THREAD

**Issue by Skyw0lf07** [ZombieStriker/QualityArmory#445] opened 2023-01-18 19:08 UTC
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

The plugin was working and now all the weapons have unlimited ammo out of nowhere...

The only plugins that I've installed recently were spartan ac, jetsantiafkpro and dinovoterewards

### Expected Behaviour

Ammo isn't being used

### Plugins

Spartan, Dinovoterewards, Jetsantiafkpro

### Server Version

1.17.1

**Comment by matytyma** [comment] 2023-01-22 12:26
@Lorenzo0111 This happens to more people and only with the latest plugin version.

**Comment by matytyma** [comment] 2023-01-29 15:34
Hello, @Skyw0lf07 does this happen in single fire more, auto fire more or both? If only single fire mode, we'll mark this as a duplicate of #437 and continue there.

**Comment by Lorenzo0111** [comment] 2023-04-08 13:26
Duplicate of #437

**Closed by Lorenzo0111** 2023-04-08 13:26 UTC
Labels: bug, status: needs triage
