### ISSUE TITLE
[Bug]: Console error when aiming a player with a gun

### ISSUE THREAD

**Issue by KahpotVanilla** [ZombieStriker/QualityArmory#283] opened 2022-02-16 20:15 UTC
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

Pasting a console error while aiming a player with a gun. 

### Expected Behaviour

When aiming at the player, no console error should appear 

### Plugins

WorldGuard

### Server Version

1.18.1 Java 17 

### Relevant log output

```shell
[21:13:41 WARN]: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.getOrCreateTag()
[21:13:41 WARN]:        at java.base/java.lang.Class.getMethod(Class.java:2227)
[21:13:41 WARN]:        at QualityArmory.jar//me.zombie_striker.qg.handlers.ProtocolLibHandler$2.onPacketSending(ProtocolLibHandler.java:128)
[21:13:41 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[21:13:41 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[21:13:41 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535)
[21:13:41 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516)
[21:13:41 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346)
[21:13:41 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308)
[21:13:41 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:436)
[21:13:41 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:72)
[21:13:41 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:376)
[21:13:41 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:346)
[21:13:41 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[21:13:41 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[21:13:41 WARN]:        at net.minecraft.network.NetworkManager.writePacket(NetworkManager.java:401)
[21:13:41 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:348)
[21:13:41 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2022)
[21:13:41 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2008)
[21:13:41 WARN]:        at net.minecraft.server.level.PlayerChunkMap$EntityTracker.a(PlayerChunkMap.java:2296)
[21:13:41 WARN]:        at net.minecraft.server.level.PlayerChunkMap.a(PlayerChunkMap.java:2118)
[21:13:41 WARN]:        at net.minecraft.server.level.ChunkProviderServer.b(ChunkProviderServer.java:1176)
[21:13:41 WARN]:        at net.minecraft.world.entity.EntityLiving.b(EntityLiving.java:3081)
[21:13:41 WARN]:        at net.minecraft.world.entity.EntityLiving.x(EntityLiving.java:2993)
[21:13:41 WARN]:        at net.minecraft.world.entity.EntityLiving.k(EntityLiving.java:2895)
[21:13:41 WARN]:        at net.minecraft.world.entity.player.EntityHuman.k(EntityHuman.java:268)
[21:13:41 WARN]:        at net.minecraft.server.level.EntityPlayer.l(EntityPlayer.java:669)
[21:13:41 WARN]:        at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:314)
[21:13:41 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:526)
[21:13:41 WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:201)
[21:13:41 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1636)
[21:13:41 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480)
[21:13:41 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470)
[21:13:41 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264)
[21:13:41 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[21:13:41 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Lorenzo0111** [comment] 2022-02-18 06:16
Duplicate of #281

**Closed by Lorenzo0111** 2022-02-18 06:16 UTC
Labels: bug, status: needs triage
