### ISSUE TITLE
[Bug]:  Ammo is not wasted in single-shot mode

### ISSUE THREAD

**Issue by StonFlip** [ZombieStriker/QualityArmory#437] opened 2023-01-07 13:50 UTC
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

**Ammo is not wasted in single-shot mode**

If you press the shift and shoot in the sight mode, then the cartridges will be wasted, but they are not wasted if you shoot single cartridges without a shift

video:  https://imgur.com/a/uLC1iAN

### Expected Behaviour

This appeared after updating the plugin to a new version

### Plugins

 not required

### Server Version

1.16.5 Paper

### Relevant log output

```shell
the error does not show anything in the logs
```

**Comment by StonFlip** [comment] 2023-01-07 13:56
Also, when crafting/buying/giving away a weapon, it comes without ammo

**Comment by Lorenzo0111** [comment] 2023-04-08 13:30
Duplicate of #450

**Closed by Lorenzo0111** 2023-04-08 13:30 UTC
Labels: bug, status: needs triage
