### ISSUE TITLE
Can't see any item on shop / resourcepack not downloading

### ISSUE THREAD

**Issue by LightningHyperBlaze45654** [ZombieStriker/QualityArmory#211] opened 2021-11-27 02:59 UTC
No item is on shop. Bukkit 1.17.1 server.
the log has some Errors!
```
 Error occurred while enabling QualityArmory v2.0.3 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldguard/protection/flags/Flag
        at me.zombie_striker.qg.hooks.protection.ProtectionHandler.init(ProtectionHandler.java:17) ~[?:?]
        at me.zombie_striker.qg.QAMain.onEnable(QAMain.java:636) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:3281-Bukkit-eb14700]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[server.jar:3281-Bukkit-eb14700]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[server.jar:3281-Bukkit-eb14700]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:506) ~[server.jar:3281-Bukkit-eb14700]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[server.jar:3281-Bukkit-eb14700]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:609) ~[server.jar:3281-Bukkit-eb14700]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:253) ~[server.jar:3281-Bukkit-eb14700]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:987) ~[server.jar:3281-Bukkit-eb14700]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:295) ~[server.jar:3281-Bukkit-eb14700]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.protection.flags.Flag
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[server.jar:3281-Bukkit-eb14700]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[server.jar:3281-Bukkit-eb14700]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 12 more
[11:54:16] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[11:54:17] [Server thread/INFO]: Done (19.455s)! For help, type "help"
[11:57:44] [Server thread/INFO]: Hyperblaze456[/127.0.0.1:61110] logged in with entity id 24 at ([world]283.1712365126393, 29.0, -684.4401416659427)
[11:57:49] [Server thread/INFO]: Hyperblaze456 issued server command: /qa
[11:58:06] [Server thread/INFO]: Hyperblaze456 issued server command: /qa shop
[11:58:10] [Server thread/INFO]: Hyperblaze456 issued server command: /qa getResourcepack
[11:58:10] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'qa' in plugin QualityArmory v2.0.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[server.jar:3281-Bukkit-eb14700]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[server.jar:3281-Bukkit-eb14700]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:769) ~[server.jar:3281-Bukkit-eb14700]
        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1881) ~[server.jar:3281-Bukkit-eb14700]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1734) ~[server.jar:3281-Bukkit-eb14700]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1715) ~[server.jar:3281-Bukkit-eb14700]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:29) ~[server.jar:3281-Bukkit-eb14700]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[server.jar:3281-Bukkit-eb14700]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[server.jar:3281-Bukkit-eb14700]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[server.jar:3281-Bukkit-eb14700]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[server.jar:3281-Bukkit-eb14700]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:3281-Bukkit-eb14700]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[server.jar:3281-Bukkit-eb14700]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1105) ~[server.jar:3281-Bukkit-eb14700]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1098) ~[server.jar:3281-Bukkit-eb14700]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134) ~[server.jar:3281-Bukkit-eb14700]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1082) ~[server.jar:3281-Bukkit-eb14700]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1018) ~[server.jar:3281-Bukkit-eb14700]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:295) ~[server.jar:3281-Bukkit-eb14700]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "me.zombie_striker.qg.config.MessagesYML.set(String, Object)" because "me.zombie_striker.qg.QAMain.resourcepackwhitelist" is null
        at me.zombie_striker.qg.QAMain.onCommand(QAMain.java:1420) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:3281-Bukkit-eb14700]
        ... 19 more
```

does this means that this plugin needs worldguard?
idk but need some answers

**Comment by Lorenzo0111** [comment] 2021-11-27 14:28
Duplicate of #208

**Closed by Lorenzo0111** 2021-11-27 14:28 UTC
Labels: duplicate
