### ISSUE TITLE
[Bug]: Ammo is not wasted in single-shot mode (if EnableWeaponDurability: true)

### ISSUE THREAD

**Issue by Felson999** [ZombieStriker/QualityArmory#450] opened 2023-02-06 00:22 UTC
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

If you press the shift and shoot in the sight mode, then the cartridges will be wasted, but they are not wasted if you shoot single cartridges without a shift. (This problem remains if only the EnableWeaponDurability is true)

video: https://imgur.com/a/FAtAsE5

### Expected Behaviour

...

### Plugins

...

### Server Version

1.17.1

**Comment by Felson999** [comment] 2023-02-10 10:06
@Lorenzo0111 up

**Comment by matytyma** [comment] 2023-02-11 09:27
Hello, @Felson999, isn't this duplicate of #437? If so, please close this issue and continue there. Also, could you please try it in survival mode?

**Comment by Felson999** [comment] 2023-02-11 23:07
> Hello, @Felson999, isn't this duplicate of #437? If so, please close this issue and continue there. Also, could you please try it in survival mode?

Certainly not a duplicate. Read carefully. Lorenzo fixed it, but not in this case like mine. The gamemode doesn't matter.

**Closed** 2023-04-08 14:28 UTC
Labels: bug, status: accepted
