### ISSUE TITLE
[Feature]: Aim Animation

### ISSUE THREAD

**Issue by xCraimax** [ZombieStriker/QualityArmory#470] opened 2023-03-31 20:06 UTC
### Confirmations

- [X] There isn't any other PR or issue regarding this.
- [X] This feature does not exist in the latest version.

### What is your request about?

New mechanic

### Description

A feature that shows the aiming player as aiming (crossbow animation) to other player.

**Comment by Lorenzo0111** [comment] 2023-04-08 14:28
Do you have an image or an example?

**Comment by Lorenzo0111** [comment] 2023-04-08 14:31
Also duplicate of #463. Please use that

**Comment by Lorenzo0111** [comment] 2023-04-08 14:31
Duplicate of #463. Please use that

**Comment by Lorenzo0111** [comment] 2023-04-08 14:31
Duplicate of #463

**Closed by Lorenzo0111** 2023-04-08 14:31 UTC
Labels: enhancement
